// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqdKLtt0isLnGEPFXFpQdgHsR4ZMGqwSs',
    appId: '1:106532515641:web:8ff0e857ed7e5e8ce982e8',
    messagingSenderId: '106532515641',
    projectId: 'commentapp-25e13',
    authDomain: 'commentapp-25e13.firebaseapp.com',
    storageBucket: 'commentapp-25e13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvPYXI8OC1L2JpvbL8kx2t8BgVig5_Irw',
    appId: '1:106532515641:android:4d5199a160de7b5ee982e8',
    messagingSenderId: '106532515641',
    projectId: 'commentapp-25e13',
    storageBucket: 'commentapp-25e13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSHu7EXnoVSZo6zbCVHCXXYFb-uD2uyuQ',
    appId: '1:106532515641:ios:ae1b0a9c6f43b907e982e8',
    messagingSenderId: '106532515641',
    projectId: 'commentapp-25e13',
    storageBucket: 'commentapp-25e13.appspot.com',
    iosBundleId: 'com.example.commentsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSHu7EXnoVSZo6zbCVHCXXYFb-uD2uyuQ',
    appId: '1:106532515641:ios:ae1b0a9c6f43b907e982e8',
    messagingSenderId: '106532515641',
    projectId: 'commentapp-25e13',
    storageBucket: 'commentapp-25e13.appspot.com',
    iosBundleId: 'com.example.commentsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqdKLtt0isLnGEPFXFpQdgHsR4ZMGqwSs',
    appId: '1:106532515641:web:288ae678052d2210e982e8',
    messagingSenderId: '106532515641',
    projectId: 'commentapp-25e13',
    authDomain: 'commentapp-25e13.firebaseapp.com',
    storageBucket: 'commentapp-25e13.appspot.com',
  );
}
